# File: .github/workflows/workflow.yml

on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1.1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push docker image to Azure Container Registry'
          uses: azure/docker-login@v1
          with:
            login-server: azuretestcontainerregistry007.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
             docker build ./python -t azuretestcontainerregistry007.azurecr.io/aimvector/python:1.0.0:${{ github.sha }}
             docker push azuretestcontainerregistry007.azurecr.io/aimvector/python:1.0.0:${{ github.sha }}
